CREATE TABLE IF NOT EXISTS db_pris_riskmanagement.DWD_IP_INDV_CUST_INFO(
CUST_ID VARCHAR(60) COMMENT 'ECIF客户编号',
CORE_NO VARCHAR(32) COMMENT '源系统客户编码',
NAME VARCHAR(60) COMMENT '姓名',
ID_TYPE VARCHAR(10) COMMENT '证件类型',
IDNUM VARCHAR(60) COMMENT '证件号码',
SEX VARCHAR(20) COMMENT '性别',
NATIONALITY VARCHAR(10) COMMENT '民族',
NATIVEPLACE VARCHAR(200) COMMENT '籍贯',
BIRTHDAY date COMMENT '出生日期',
AGE INT COMMENT '年龄',
HIGHEST_SCHOOLING VARCHAR(10) COMMENT '最高学历',
IS_EMPLOYEE VARCHAR(2) COMMENT '是否我行员工',
HOUSEADD VARCHAR(300) COMMENT '户籍地址',
PHONE_NO VARCHAR(40) COMMENT '手机号码',
CUST_TYPE VARCHAR(10) COMMENT '客户类型',
IDENT_EXPRIRED_DATE date COMMENT '证件到期日',
CUST_STAT VARCHAR(20) COMMENT '客户状态',
CUST_CLASS VARCHAR(5) COMMENT '客户类别',
ZIPCODE VARCHAR(200) COMMENT '邮政编码',
POLITICAL_FACE VARCHAR(10) COMMENT '政治面貌',
HIGHEST_DEGREE VARCHAR(10) COMMENT '最高学位',
MARRIAGE VARCHAR(10) COMMENT '婚姻状况',
RESIDENCE VARCHAR(10) COMMENT '居住状况',
CAREER_TYPE VARCHAR(10) COMMENT '从事职业',
DUTY VARCHAR(100) COMMENT '职务',
CAREER_TITLE VARCHAR(10) COMMENT '职称',
UNIT_NAME VARCHAR(200) COMMENT '工作单位',
UNIT_CHAR VARCHAR(10) COMMENT '单位性质',
PROFESSION VARCHAR(10) COMMENT '行业类别',
PER_MON_INCOME DECIMAL(22,4) COMMENT '年收入情况',
HOME_CONDITION VARCHAR(200) COMMENT '现住房类别',
HHDIST VARCHAR(20) COMMENT '户籍省份',
MAILADDR VARCHAR(300) COMMENT '通讯地址',
RESIADDR VARCHAR(200) COMMENT '居住地址',
RESIDIST VARCHAR(200) COMMENT '居住地址省份',
RESIPC VARCHAR(200) COMMENT '居住的邮政编码',
WORK_CORP_TEL VARCHAR(25) COMMENT '单位电话',
WORK_CORP_ADDR VARCHAR(1000) COMMENT '单位地址',
WORK_corp_ADDR_ZIP_CD VARCHAR(50) COMMENT '单位邮编',
ACCESSION_DT date COMMENT '单位工作起始年',
SPOUSE_NAME VARCHAR(100) COMMENT '配偶姓名',
SPOIDTYPE VARCHAR(10) COMMENT '配偶证件类型',
SPOIDNUM VARCHAR(60) COMMENT '配偶证件号码',
SPOUNIT_NAME VARCHAR(200) COMMENT '配偶工作单位',
SPOYEAR_INCOME DECIMAL(22,4) COMMENT '配偶年收入',
SPO_COMPA_PHONE VARCHAR(20) COMMENT '配偶单位联系电话',
SPOTEL VARCHAR(40) COMMENT '配偶手机号码',
SPOCUST_ID VARCHAR(20) COMMENT '配偶客户号码',
SPO_OCCUPATION VARCHAR(10) COMMENT '配偶职业',
SPO_POST VARCHAR(100) COMMENT '配偶职务',
LAST_UPDATE_DATE VARCHAR(10) COMMENT '最后更新日期',
LAST_UPDATE_TIME VARCHAR(20) COMMENT '最后更新时间',
input_date varchar(10) COMMENT '插入日期'
) PARTITIONED BY (PLATFORM_CODE varchar(100) comment '平台代码')
CLUSTERED by (CUST_ID) into 7 buckets
stored as holodesk;


/*
-- 添加单值分区
ALTER TABLE db_pris_riskmanagement.DWD_IP_INDV_CUST_INFO ADD PARTITION (PLATFORM_CODE='ECIF');
ALTER TABLE db_pris_riskmanagement.DWD_IP_INDV_CUST_INFO ADD PARTITION (PLATFORM_CODE='XXD'); --新信贷
*/

COMMENT ON TABLE db_pris_riskmanagement.DWD_IP_INDV_CUST_INFO is '当事人-客户-个人客户信息表';