-- 代偿表结构:
-- DROP TABLE IF EXISTS db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL;

CREATE TABLE IF NOT EXISTS db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL(
DATA_DT DATE COMMENT '数据日期',
DC_DT DATE COMMENT '代偿日',
PRD_CODE VARCHAR(100) COMMENT '产品编码',
PRD_NAME VARCHAR(100) COMMENT '产品名称',
LOAN_NO VARCHAR(100) COMMENT '借据编号',
DC_BAL DECIMAL(24,6) COMMENT '代偿本金',
DC_INT DECIMAL(24,6) COMMENT '代偿利息',
DC_FINC DECIMAL(24,6) COMMENT '代偿罚息',
DC_ALL_BAL DECIMAL(24,6) COMMENT '代偿总额',
DC_TERM INTEGER COMMENT '代偿期次',
DC_TYPE VARCHAR(100) COMMENT '代偿类型',
UPDATE_DATE DATE COMMENT '数据更新日期'
) COMMENT '代偿表'
PARTITIONED BY (PLATFORM_CODE VARCHAR(100) COMMENT '平台代码')
CLUSTERED BY (LOAN_NO) INTO 7 buckets
STORED AS holodesk;

/*
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'DD'); -- 大地
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'YC'); -- 永城
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'XW'); -- 新网
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'MS'); -- 马上
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'ZB'); -- 中保
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'WSD'); -- 网商
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = '360'); -- 直连360
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'WDHX'); -- 网贷核心
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'WDHXLHD'); -- 网贷核心联合贷
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'WCD'); -- 微车贷
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'ZJ01'); -- 字节

ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'WDHX_2'); -- 网贷核心
ALTER TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL ADD PARTITION (PLATFORM_CODE = 'WDHXLHD_2'); -- 网贷核心联合贷
*/

COMMENT ON TABLE db_pris_riskmanagement.DWD_SR_CLAIM_DETAIL IS '代偿表';