
create table if not exists db_pris_riskmanagement.DWD_AR_LOAN_INFO(
LOAN_NO VARCHAR(100) COMMENT '借据编码',
CONT_NO VARCHAR(100) COMMENT '合同编码',
CUST_ID VARCHAR(100) COMMENT '业务系统合同编码',
PRD_CODE VARCHAR(100) COMMENT '产品编码',
NAME VARCHAR(100) COMMENT '客户姓名',
IDTYPE VARCHAR(100) COMMENT '证件类型',
IDNUM VARCHAR(100) COMMENT '证件号码',
START_DATE DATE COMMENT '借款开始日期',
END_DATE DATE COMMENT '借款结束日期',
LOAN_STATUS VARCHAR(100) COMMENT '贷款状态',
END_SIGN INT COMMENT '停息标识',
CANCEL_REASON VARCHAR(100) COMMENT '贷款撤销原因',
PAYOFF_DATE DATE COMMENT '结清日期',
TOTAL_TERMS INT COMMENT '贷款期数',
GRACE_DAY INT COMMENT '宽限天数',
IS_DEBT_TR INT COMMENT '是否债转',
IS_DEBT_TR_DATE DATE COMMENT '债转日期',
RATE_TYPE VARCHAR(100) COMMENT '利率类型',
YEAR_RATE DECIMAL(24,6) COMMENT '年利率',
DAY_RATE DECIMAL(24,6) COMMENT '日利率',
PNLT_RATE DECIMAL(24,6) COMMENT '罚息利率',
YEAR_RATE_PROFIT DECIMAL(24,6) COMMENT '我行利率',
CAPITAL_RATIO DECIMAL(24,6) COMMENT '出资比例',
LOAN_AMT DECIMAL(24,6) COMMENT '贷款金额',
PRIN_BAL DECIMAL(24,6) COMMENT '贷款本金余额',
NORMAL_BAL DECIMAL(24,6) COMMENT '正常本金余额',
OVD_BAL DECIMAL(24,6) COMMENT '逾期本金余额',
INPUT_DATE DATE COMMENT '录入日期',
INPUT_TIME DATE COMMENT '录入时间',
LAST_UPDATE_DATE DATE COMMENT '最后更新日期',
LAST_UPDATE_TIME DATE COMMENT '最后更新时间',
DATA_DATE VARCHAR(100) COMMENT '数据日期字符串类型',
DATA_DATE_NUM VARCHAR(100) COMMENT '数据日期数字类型'
)
PARTITIONED BY (PLATFORM_CODE varchar(100) comment '平台代码')
CLUSTERED by (LOAN_NO) into 7 buckets
stored as holodesk;


/*
-- 添加单值分区
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='XXD'); --新信贷
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WS'); --网商
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WDHXLHD'); --网商
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WDHX'); --网贷核心
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='DD'); --大地
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='MS'); --马上消金
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='360'); --360分润
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='XW'); --新网
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='ZB'); --中保360
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WC'); --微车
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='FBED'); --富邦E贷
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='ZJ01'); --字节
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='ZAD'); --众安贷
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WLD'); --微粒贷
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WDHXLHD_2'); --网商
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WDHX_2'); --网贷核心
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='ZY'); --自营产品
ALTER TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO ADD PARTITION (PLATFORM_CODE='WL'); --自营产品
*/

COMMENT ON TABLE db_pris_riskmanagement.DWD_AR_LOAN_INFO is '协议-贷款借据信息-贷款借据信息表';